[package]
  cjc-version = "1.1.0"
  name = "cj_taskgroup_benchmark"
  organization = ""
  description = "Benchmarks for cj_taskgroups and Swift structured concurrency"
  version = "1.0.0"
  src-dir = "src"
  target-dir = ""
  script-dir = ""
  output-type = "executable"
  compile-option = "-O2"
  override-compile-option = ""
  link-option = ""
  package-configuration = {}
  scripts = {}

[dependencies]
  cj_taskgroups = { path = "../..", output-type = "static" }
